import { mkdir, readFile, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import type { Conversation, ConversationMeta } from '@shared/types'

const INDEX_FILE = 'index.json'
const CONFIG_FILE = 'config.json'
const CONV_DIR = 'conversations'

// Conversation ids are generated by the renderer as uuid/random strings, but they
// cross the IPC boundary and end up as filenames — reject anything that could
// escape the conversations directory before touching the filesystem.
const SAFE_ID = /^[a-zA-Z0-9_-]+$/

interface IndexFile {
  conversations: ConversationMeta[]
}

interface ConfigFile {
  lastWorkspace?: string | null
}

export interface ConversationStore {
  listMetas(workspace: string): Promise<ConversationMeta[]>
  loadConversation(id: string): Promise<Conversation | null>
  saveConversation(conv: Conversation): Promise<{ id: string }>
  deleteConversation(id: string): Promise<{ ok: boolean }>
  getLastWorkspace(): Promise<string | null>
  setLastWorkspace(path: string): Promise<{ ok: boolean }>
}

export function createConversationStore(userDataDir: string): ConversationStore {
  const convDir = join(userDataDir, CONV_DIR)
  const indexPath = join(convDir, INDEX_FILE)
  const configPath = join(userDataDir, CONFIG_FILE)

  async function ensureConvDir(): Promise<void> {
    await mkdir(convDir, { recursive: true })
  }

  async function readIndex(): Promise<IndexFile> {
    try {
      const raw = await readFile(indexPath, 'utf8')
      const parsed = JSON.parse(raw) as IndexFile
      if (!parsed || !Array.isArray(parsed.conversations)) return { conversations: [] }
      return parsed
    } catch {
      return { conversations: [] }
    }
  }

  async function writeIndex(data: IndexFile): Promise<void> {
    await ensureConvDir()
    await writeFile(indexPath, JSON.stringify(data, null, 2), 'utf8')
  }

  async function readConfig(): Promise<ConfigFile> {
    try {
      const raw = await readFile(configPath, 'utf8')
      const parsed = JSON.parse(raw) as ConfigFile
      return parsed && typeof parsed === 'object' ? parsed : {}
    } catch {
      return {}
    }
  }

  async function writeConfig(data: ConfigFile): Promise<void> {
    await mkdir(userDataDir, { recursive: true })
    await writeFile(configPath, JSON.stringify(data, null, 2), 'utf8')
  }

  return {
    async listMetas(workspace): Promise<ConversationMeta[]> {
      const { conversations } = await readIndex()
      return conversations
        .filter(c => c.workspace === workspace)
        .sort((a, b) => b.updatedAt - a.updatedAt)
    },

    async loadConversation(id): Promise<Conversation | null> {
      if (!SAFE_ID.test(id)) return null
      try {
        const raw = await readFile(join(convDir, `${id}.json`), 'utf8')
        const parsed = JSON.parse(raw) as Conversation
        if (!parsed || !Array.isArray(parsed.messages)) return null
        return parsed
      } catch {
        return null
      }
    },

    async saveConversation(conv): Promise<{ id: string }> {
      if (!SAFE_ID.test(conv.id)) {
        throw new Error(`Invalid conversation id: ${conv.id}`)
      }
      await ensureConvDir()
      await writeFile(join(convDir, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf8')

      const { conversations } = await readIndex()
      const meta: ConversationMeta = {
        id: conv.id,
        title: conv.title,
        workspace: conv.workspace,
        createdAt: conv.createdAt,
        updatedAt: conv.updatedAt
      }
      const idx = conversations.findIndex(c => c.id === conv.id)
      const next =
        idx >= 0
          ? [...conversations.slice(0, idx), meta, ...conversations.slice(idx + 1)]
          : [...conversations, meta]
      await writeIndex({ conversations: next })
      return { id: conv.id }
    },

    async deleteConversation(id): Promise<{ ok: boolean }> {
      if (!SAFE_ID.test(id)) return { ok: false }
      try {
        await rm(join(convDir, `${id}.json`), { force: true })
      } catch {
        // best-effort; still drop from index below
      }
      const { conversations } = await readIndex()
      const next = conversations.filter(c => c.id !== id)
      if (next.length !== conversations.length) {
        await writeIndex({ conversations: next })
      }
      return { ok: true }
    },

    async getLastWorkspace(): Promise<string | null> {
      const cfg = await readConfig()
      return cfg.lastWorkspace ?? null
    },

    async setLastWorkspace(path): Promise<{ ok: boolean }> {
      await writeConfig({ lastWorkspace: path })
      return { ok: true }
    }
  }
}
